version: "3.5"

services:
  mysql:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: databiz
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the initialization script

  api:
    build:
      dockerfile: Dockerfile.backend
      context: "./"
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=databiz
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  client:
    build:
      dockerfile: Dockerfile.frontend
      context: ./front-app
    volumes:
      - /app/node_modules
      - ./front-app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3000"

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
